/**
 * AI-ready project context (Phase 4 §7).
 *
 * The second renderer over `DocumentationModel`. Same model as the human
 * Technical Notes, so the two cannot describe different projects — which is the
 * whole reason §9 puts a model between the IPS and its documents.
 *
 * ## What "AI-ready" means here, and what it does not
 *
 * §27 is explicit: this is *documentation formatted for AI consumption*, not an
 * AI product. Nothing here calls a model, and nothing here is generated by one.
 * It is a deterministic serialisation a developer pastes into an assistant.
 *
 * ## Five properties §7 asks for, and how each is met
 *
 * | Property | How |
 * | --- | --- |
 * | deterministic | no clock, no randomness, no unordered iteration; **definition only** — see below |
 * | structured | `Key: value` for scalars, `- a \| b \| c` for repeated records |
 * | concise | pipe-delimited fields, dotted paths, no repeated labels |
 * | explicit | every endpoint states public/protected; auth states disabled outright |
 * | unambiguous | one fact per line, fixed field order, no prose that could be read as data |
 *
 * ## No runtime block, deliberately
 *
 * The human notes carry an optional `## Current state` section — status,
 * published version, a timestamp. This document has none. §7 requires output
 * "stable across repeated generation", and status moves without the definition
 * changing, so including it would make two exports of an unchanged project
 * differ. An assistant asked to write client code has no use for it either.
 *
 * ## No prose
 *
 * §7 forbids assistant-style filler ("Here is a detailed overview…"). There is
 * no sentence in the output that is not a fact about the project, which also
 * means a consumer never has to decide whether a line is data or commentary.
 */

import type { DocumentationModel, NotesEndpoint, NotesField, NotesRelation } from './notes-model.js';
import { flattenFields } from './notes-model.js';

export interface AiContextOptions {
  /**
   * Hosted base URL, when the caller knows it.
   *
   * Genuinely useful to an assistant writing `fetch` calls, and omitted rather
   * than guessed: the base is deployment configuration, and a wrong URL in a
   * context document produces client code that fails against the real API.
   */
  baseUrl?: string | undefined;
}

/** `min=18` rules and traits, pipe-joined; empty string when there are none. */
function fieldAttributes(field: NotesField): string[] {
  return [
    field.required ? 'required' : 'optional',
    // `hasDefault`, not `default !== undefined`: the parsers write `null` as
    // their unset value, so testing the value directly would print
    // `default=null` on almost every field — a default the generated validators
    // never apply. See `NotesField.hasDefault`.
    ...(field.hasDefault ? [`default=${JSON.stringify(field.default)}`] : []),
    ...field.validation.rules,
    // Traits carry the arrow form (`foreign key → Course`); the arrow is fine
    // in a pipe-delimited line and tells an assistant which entity a key points
    // at without it having to infer from the name.
    ...field.traits,
  ];
}

/**
 * One field, on one line.
 *
 * Nested fields use their **dotted path** rather than indentation. §7's example
 * shows a flat list, and indentation inside a pipe-delimited list is genuinely
 * ambiguous to parse — two spaces could be structure or formatting. A dotted
 * path is unambiguous, and it is also the exact string the runtime's query
 * layer and the diff engine use for a nested field, so an assistant reading
 * this and an error message from the API are talking about the same thing.
 */
function renderField(field: NotesField): string {
  return `- ${field.path} | ${field.type} | ${fieldAttributes(field).join(' | ')}`;
}

function renderRelation(relation: NotesRelation): string {
  return (
    `- ${relation.source}.${relation.name} -> ${relation.target}.${relation.foreignField} | ` +
    `${relation.cardinality} | via ${relation.source}.${relation.localField} | ` +
    `on-delete=${relation.onDelete}`
  );
}

/**
 * One endpoint, with its access requirement stated on every line.
 *
 * §25 requires "explicit endpoint visibility". Stating it per endpoint rather
 * than once per entity is what makes each line independently true — an
 * assistant that reads only the `## APIs` section still knows which calls need
 * a token, and a line copied out of context does not lose its meaning.
 */
function renderEndpoint(endpoint: NotesEndpoint): string {
  const parts = [
    `${endpoint.method} ${endpoint.path}`,
    endpoint.requiresAuth ? 'protected' : 'public',
    ...(endpoint.requestEntity === null ? [] : [`body=${endpoint.requestEntity}`]),
    ...(endpoint.pathParams.length > 0 ? [`path=${endpoint.pathParams.join(',')}`] : []),
    ...(endpoint.queryParams.length > 0 ? [`query=${endpoint.queryParams.join(',')}`] : []),
    `response=${endpoint.responseShape}`,
  ];
  return `- ${parts.join(' | ')}`;
}

/**
 * Render the AI-ready context document.
 *
 * Carries no secret by construction: `DocumentationModel` has no field for one
 * (see `NotesAuth`), so there is nothing here to redact.
 */
export function renderAiContext(model: DocumentationModel, options: AiContextOptions = {}): string {
  const { project, auth, generation } = model;
  const out: string[] = [];

  out.push('# Project Context', '');

  out.push('## Project');
  out.push(`Name: ${project.name || 'unnamed'}`);
  if (project.description !== null && project.description !== '') {
    out.push(`Description: ${project.description}`);
  }
  out.push(`Type: ${project.kind}`);
  out.push(`Version: ${project.version}`);
  if (options.baseUrl !== undefined && options.baseUrl !== '') {
    out.push(`Base URL: ${options.baseUrl}`);
  }
  out.push('');

  out.push('## Authentication');
  if (!auth.enabled) {
    /*
     * §25: "explicit auth state". One line, and the same line every time, so a
     * consumer can match on it rather than inferring from a missing section —
     * an absent heading reads as "not documented", which is a different claim.
     */
    out.push('Enabled: false');
    out.push('Note: every endpoint is public; no token is required.');
  } else {
    out.push('Enabled: true');
    out.push(`Mode: ${auth.mode}`);
    out.push(`Cookie Auth: ${auth.cookieAuth}`);
    out.push(`Access Token TTL: ${auth.accessTokenExpiresIn}`);
    out.push(`Refresh Token TTL: ${auth.refreshTokenExpiresIn}`);
    out.push(
      `Protected Entities: ${
        auth.protectedEntities.length === 0 ? 'none' : auth.protectedEntities.join(',')
      }`,
    );
    out.push('');
    out.push('### Auth Endpoints');
    for (const endpoint of auth.endpoints) {
      out.push(
        `- ${endpoint.method} ${endpoint.path} | ${
          endpoint.requiresToken ? 'protected' : 'public'
        }`,
      );
    }
    if (auth.userFields.length > 0) {
      out.push('');
      out.push('### Sign-up Fields');
      out.push('Collected in addition to email and password.');
      for (const field of auth.userFields) {
        out.push(`- ${field.name} | ${field.type} | ${field.required ? 'required' : 'optional'}`);
      }
    }
  }
  out.push('');

  out.push('## Entities');
  if (model.entities.length === 0) {
    // Stated, not omitted: an Auth API project genuinely has none, and silence
    // would read as truncated output.
    out.push('None. This project has no entities.');
    out.push('');
  } else {
    for (const entity of model.entities) {
      out.push('');
      out.push(`### ${entity.name}`);
      out.push(`ID: ${entity.id ?? 'none'}`);
      if (entity.description !== null && entity.description !== '') {
        out.push(`Description: ${entity.description}`);
      }
      out.push(`Path: /${entity.path}`);
      out.push(`Authentication: ${entity.requiresAuth ? 'protected' : 'public'}`);
      out.push(`Identity: ${entity.identity.field} (${entity.identity.style})`);
      out.push('');
      out.push('#### Fields');
      // Flattened, so a nested field is one line with a dotted path rather than
      // a shape a consumer has to walk.
      for (const field of flattenFields(entity.fields)) {
        out.push(renderField(field));
      }
    }
    out.push('');
  }

  out.push('## Relationships');
  if (model.relations.length === 0) {
    out.push('None.');
  } else {
    for (const relation of model.relations) {
      out.push(renderRelation(relation));
    }
  }
  out.push('');

  out.push('## APIs');
  if (model.endpoints.length === 0) {
    out.push('None.');
  } else {
    for (const endpoint of model.endpoints) {
      out.push(renderEndpoint(endpoint));
    }
  }
  out.push('');

  out.push('## Generation');
  out.push(`Methods: ${generation.methods.join(',') || 'none'}`);
  out.push(`Validators: ${generation.validators.join(',') || 'none'}`);
  out.push(`Types: ${generation.types.join(',') || 'none'}`);
  out.push(`Mock Records Per Entity: ${generation.mockRecords}`);
  const enabledFeatures = (['search', 'filter', 'sort', 'include'] as const).filter(
    (feature) => generation.features[feature],
  );
  out.push(`Query Features: ${enabledFeatures.join(',') || 'none'}`);

  return `${out.join('\n').trimEnd()}\n`;
}
